### ISSUE TITLE
Detect the default branch automatically

### ISSUE THREAD

**Issue by eregon** [eregon/truffleruby-gem-tracker#3]
Currently we workaround with things like `branch: main` but it is quite error prone.
We should use the GitHub API to fetch the default branch and use that instead of manually specifying the `branch:`.

**Comment by eregon** [comment]
@bjfish Could you take a look at this?

**Comment by bjfish** [comment]
I implemented this for GitHub CI here: https://github.com/eregon/truffleruby-gem-tracker/commit/33bc07a8c5ead8b70ab3a7aad24349a18de09b9e

**Comment by eregon** [comment]
Awesome, thanks!
